### ISSUE TITLE
error : Cannot find module 'adm-zip' [...\build\cmakebuild.vcxproj]

### ISSUE THREAD

**Issue by TwoAbove** [lyssdod/node-libtorrent#9]
Hey! Really interested in the project, but installing from source gives me this error:
```
CUSTOMBUILD : error : Cannot find module 'adm-zip' [D:\Work\newtor\client\node_modules\node-libtorrent-ng\build\cmakebuild.vcxproj]
      at Function.Module._resolveFilename (module.js:485:15)
      at Function.Module._load (module.js:437:25)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (D:\Work\newtor\client\node_modules\node-libtorrent-ng\compile.js:10:14)
      at Module._compile (module.js:569:30)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:503:32)
      at tryModuleLoad (module.js:466:12)
      at Function.Module._load (module.js:458:3)
```
I'm installing with 
`npm i --save https://github.com/lyssdod/node-libtorrent/archive/0.4.7.tar.gz`

Looks like a simple deps issue.

**Comment by TwoAbove** [comment]
Closed because old
